// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StajyerTakipSistemi.Data;

#nullable disable

namespace StajyerTakipSistemi.Migrations
{
    [DbContext(typeof(StajyerTakipDbContext))]
    [Migration("20250806071024_InitialCreateCleaned")]
    partial class InitialCreateCleaned
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StajyerTakipSistemi.Models.Egitim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EgitimAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Saat")
                        .HasColumnType("time");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Egitimler");
                });

            modelBuilder.Entity("StajyerTakipSistemi.Models.Gorev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EgitmenId")
                        .HasColumnType("int");

                    b.Property<string>("GorevAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EgitmenId");

                    b.ToTable("Gorevler");
                });

            modelBuilder.Entity("StajyerTakipSistemi.Models.ProjeAdimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StajyerId")
                        .HasColumnType("int");

                    b.Property<bool>("Tamamlandi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StajyerId");

                    b.ToTable("ProjeAdimlari");
                });

            modelBuilder.Entity("StajyerTakipSistemi.Models.Stajyer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Bolum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CVDosyasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<string>("FotografDosyasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OgrenciBelgesiDosyasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OkulAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SigortaGirisDosyasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sinif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StajTuru")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Stajyerler");
                });

            modelBuilder.Entity("StajyerTakipSistemi.Models.StajyerGorev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtamaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GorevId")
                        .HasColumnType("int");

                    b.Property<int>("StajyerId")
                        .HasColumnType("int");

                    b.Property<bool>("Tamamlandi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("TamamlanmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GorevId");

                    b.HasIndex("StajyerId");

                    b.ToTable("StajyerGorevler");
                });

            modelBuilder.Entity("StajyerTakipSistemi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BasvuruDurumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BasvuruTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Bolum")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CVDosyaYolu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FotografDosyaYolu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("OkulAdi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sinif")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("StajBaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StajBitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("StajTuru")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StajyerTakipSistemi.Models.Gorev", b =>
                {
                    b.HasOne("StajyerTakipSistemi.Models.User", "Egitmen")
                        .WithMany()
                        .HasForeignKey("EgitmenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Egitmen");
                });

            modelBuilder.Entity("StajyerTakipSistemi.Models.ProjeAdimi", b =>
                {
                    b.HasOne("StajyerTakipSistemi.Models.Stajyer", "Stajyer")
                        .WithMany()
                        .HasForeignKey("StajyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stajyer");
                });

            modelBuilder.Entity("StajyerTakipSistemi.Models.Stajyer", b =>
                {
                    b.HasOne("StajyerTakipSistemi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StajyerTakipSistemi.Models.StajyerGorev", b =>
                {
                    b.HasOne("StajyerTakipSistemi.Models.Gorev", "Gorev")
                        .WithMany("StajyerGorevler")
                        .HasForeignKey("GorevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StajyerTakipSistemi.Models.Stajyer", "Stajyer")
                        .WithMany("StajyerGorevler")
                        .HasForeignKey("StajyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gorev");

                    b.Navigation("Stajyer");
                });

            modelBuilder.Entity("StajyerTakipSistemi.Models.Gorev", b =>
                {
                    b.Navigation("StajyerGorevler");
                });

            modelBuilder.Entity("StajyerTakipSistemi.Models.Stajyer", b =>
                {
                    b.Navigation("StajyerGorevler");
                });
#pragma warning restore 612, 618
        }
    }
}
