// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StajyerTakipSistemi.Data;

#nullable disable

namespace StajyerTakipSistemi.Migrations
{
    [DbContext(typeof(StajyerTakipDbContext))]
    partial class StajyerTakipDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StajyerTakipSistemi.Models.Egitim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EgitimAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Saat")
                        .HasColumnType("time");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Egitimler");
                });

            modelBuilder.Entity("StajyerTakipSistemi.Models.EgitimKatilimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtamaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("EgitimId")
                        .HasColumnType("int");

                    b.Property<bool?>("KatildiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("KatilimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KatilmamaNedeni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StajyerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EgitimId");

                    b.HasIndex("StajyerId");

                    b.ToTable("EgitimKatilimlari");
                });

            modelBuilder.Entity("StajyerTakipSistemi.Models.EgitmenDuyurusu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EgitmenId")
                        .HasColumnType("int");

                    b.Property<int>("HedefKitle")
                        .HasColumnType("int");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EgitmenId");

                    b.ToTable("EgitmenDuyurulari");
                });

            modelBuilder.Entity("StajyerTakipSistemi.Models.Gorev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EgitmenId")
                        .HasColumnType("int");

                    b.Property<string>("GorevAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TeslimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZorlukSeviyesi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EgitmenId");

                    b.ToTable("Gorevler");
                });

            modelBuilder.Entity("StajyerTakipSistemi.Models.OdevMesaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EkDosyaYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GonderenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GonderimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OdevTeslimId")
                        .HasColumnType("int");

                    b.Property<bool>("Okundu")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GonderenId");

                    b.HasIndex("OdevTeslimId");

                    b.ToTable("OdevMesajlar");
                });

            modelBuilder.Entity("StajyerTakipSistemi.Models.OdevTeslim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DegerlendirmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("DosyaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DosyaBoyutu")
                        .HasColumnType("bigint");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<string>("EgitmenGeriBildirimi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Puan")
                        .HasColumnType("int");

                    b.Property<int>("StajyerGorevId")
                        .HasColumnType("int");

                    b.Property<string>("StajyerNotu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TeslimTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StajyerGorevId");

                    b.ToTable("OdevTeslimler");
                });

            modelBuilder.Entity("StajyerTakipSistemi.Models.SistemBildirimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IlgiliId")
                        .HasColumnType("int");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Okundu")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("StajyerId")
                        .HasColumnType("int");

                    b.Property<int>("Tur")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StajyerId");

                    b.ToTable("SistemBildirimleri");
                });

            modelBuilder.Entity("StajyerTakipSistemi.Models.StajyerGorev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtamaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GorevId")
                        .HasColumnType("int");

                    b.Property<bool>("Tamamlandi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("TamamlanmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GorevId");

                    b.HasIndex("UserId");

                    b.ToTable("StajyerGorevler");
                });

            modelBuilder.Entity("StajyerTakipSistemi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BasvuruDurumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BasvuruTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Bolum")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CVDosyaYolu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FotografDosyaYolu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("OkulAdi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sinif")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("StajBaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StajBitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("StajTuru")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StajyerTakipSistemi.Models.EgitimKatilimi", b =>
                {
                    b.HasOne("StajyerTakipSistemi.Models.Egitim", "Egitim")
                        .WithMany("Katilimlar")
                        .HasForeignKey("EgitimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StajyerTakipSistemi.Models.User", "Stajyer")
                        .WithMany()
                        .HasForeignKey("StajyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Egitim");

                    b.Navigation("Stajyer");
                });

            modelBuilder.Entity("StajyerTakipSistemi.Models.EgitmenDuyurusu", b =>
                {
                    b.HasOne("StajyerTakipSistemi.Models.User", "Egitmen")
                        .WithMany()
                        .HasForeignKey("EgitmenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Egitmen");
                });

            modelBuilder.Entity("StajyerTakipSistemi.Models.Gorev", b =>
                {
                    b.HasOne("StajyerTakipSistemi.Models.User", "Egitmen")
                        .WithMany()
                        .HasForeignKey("EgitmenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Egitmen");
                });

            modelBuilder.Entity("StajyerTakipSistemi.Models.OdevMesaj", b =>
                {
                    b.HasOne("StajyerTakipSistemi.Models.User", "Gonderen")
                        .WithMany()
                        .HasForeignKey("GonderenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StajyerTakipSistemi.Models.OdevTeslim", "OdevTeslim")
                        .WithMany("Mesajlar")
                        .HasForeignKey("OdevTeslimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gonderen");

                    b.Navigation("OdevTeslim");
                });

            modelBuilder.Entity("StajyerTakipSistemi.Models.OdevTeslim", b =>
                {
                    b.HasOne("StajyerTakipSistemi.Models.StajyerGorev", "StajyerGorev")
                        .WithMany()
                        .HasForeignKey("StajyerGorevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StajyerGorev");
                });

            modelBuilder.Entity("StajyerTakipSistemi.Models.SistemBildirimi", b =>
                {
                    b.HasOne("StajyerTakipSistemi.Models.User", "Stajyer")
                        .WithMany()
                        .HasForeignKey("StajyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stajyer");
                });

            modelBuilder.Entity("StajyerTakipSistemi.Models.StajyerGorev", b =>
                {
                    b.HasOne("StajyerTakipSistemi.Models.Gorev", "Gorev")
                        .WithMany("StajyerGorevler")
                        .HasForeignKey("GorevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StajyerTakipSistemi.Models.User", "User")
                        .WithMany("AtananGorevler")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gorev");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StajyerTakipSistemi.Models.Egitim", b =>
                {
                    b.Navigation("Katilimlar");
                });

            modelBuilder.Entity("StajyerTakipSistemi.Models.Gorev", b =>
                {
                    b.Navigation("StajyerGorevler");
                });

            modelBuilder.Entity("StajyerTakipSistemi.Models.OdevTeslim", b =>
                {
                    b.Navigation("Mesajlar");
                });

            modelBuilder.Entity("StajyerTakipSistemi.Models.User", b =>
                {
                    b.Navigation("AtananGorevler");
                });
#pragma warning restore 612, 618
        }
    }
}
